# ============================================================
# ansible/inventory/hosts.yml
# Inventaire statique — IPs issues du terraform output
# NOTE: Dans le pipeline CI/CD, ce fichier est régénéré
#       dynamiquement depuis les outputs Terraform.
# ============================================================
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/pfs-soc-key

  children:
    # ── VPC SOC ─────────────────────────────────────────────
    soc:
      vars:
        wazuh_manager_ip: 10.1.1.133
      hosts:
        wazuh-server:
          ansible_host: 10.1.1.133
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
            -o ProxyJump=ubuntu@54.162.134.225

    # ── VPC Client (subnet privé) ────────────────────────────
    client:
      vars:
        wazuh_manager_ip: 10.1.1.133  # IP privée du Wazuh server (VPC peering)
      hosts:
        dvwa:
          ansible_host: 10.0.2.98
          # wazuh_agent_name : nom de l'agent dans Wazuh (≠ inventory_hostname)
          # Évite les conflits lors des re-déploiements
          wazuh_agent_name: dvwa-apache
          # is_dvwa_host : conditionnel pour le template ossec.conf
          # → surveille /var/log/dvwa-access.log (logs Docker forwardés)
          is_dvwa_host: true
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
            -o ProxyJump=ubuntu@54.162.134.225

        metasploitable:
          ansible_host: 10.0.2.80
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
            -o ProxyJump=ubuntu@54.162.134.225

