# ============================================================
# ansible/inventory/hosts.yml
# Inventaire statique — IPs issues du terraform output
# ============================================================
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/pfs-soc-key

  children:
    # ── VPC SOC ─────────────────────────────────────────────
    soc:
      hosts:
        wazuh-server:
          ansible_host: 10.1.1.109
          # Wazuh est dans le VPC SOC — accès via bastion (ProxyJump)
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
            -o ProxyJump=ubuntu@32.194.75.46

    # ── VPC Client (subnet privé) ────────────────────────────
    client:
      hosts:
        dvwa:
          ansible_host: 10.0.2.206
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
            -o ProxyJump=ubuntu@32.194.75.46

        metasploitable:
          ansible_host: 10.0.2.141
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
            -o ProxyJump=ubuntu@32.194.75.46
